#Different data type
print ("Numbers")
print (type(5))
print (type(2.5))
print (type(3+4j))
print (type("Julieta"))
print (type(True))
print (type (["primer día de python","cantidad de ejercicios", 2 ]))
print (type ({'proyecto':'30 días de python','fecha de inicio':'2/09/2021'}))
print (type (('Julieta','frontend')))